version: "3.7"
services:
  db:
    platform: linux/amd64
    build: ./database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sectimes
    ports:
      - 8001:3306
    # networks:
    #   - sectimes
  app:
    links:
      - db
    build:
      args:
        user: sectimes
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    working_dir: /var/www/
    command: php artisan serve --host=0.0.0.0 --port=8000
    volumes:
      - ./:/var/www
    # networks:
    #   - sectimes

# networks:
#   sectimes: